name: GraalVM build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: "17" # See 'Options' section below for all supported versions
          distribution: "graalvm" # See 'Options' section below for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print env before build
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
          ls -lart
      - name: Maven generate graalvm native executable x86
        run: mvn -e native:compile -Pnative -Dmaven.test.skip=true # -DmainClass=com.tailuge.lobby.LobbyApplication
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Show directory after build
        run: ls -lart ./
      - name: Show targetdirectory after build
        run: ls -lart ./target/
      - name: Show docker images before docker is run
        run: docker images
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: tailuge/lobby:latest
      - name: Show docker images after docker is run
        run: docker images
