# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: produced JAR in ./target 
        run: ls -lart ./target
      - name: Create docker image for arm64
        run: docker build -f Dockerfile.arm64 -t lobby-jre:latest .
      - name: debug  
        run: docker images
      - name: Tag Docker Image
        run: docker tag lobby-jre:latest ${{ secrets.DOCKER_USERNAME }}/lobby-jre:latest
      - name: debug  
        run: docker images
#      - name: Push graalvm native Docker Image
#        run: docker push ${{ secrets.DOCKER_USERNAME }}/lobby:0.0.1-SNAPSHOT
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          build: false
          push: true
          tags: tailuge/lobby-jre:latest